CREATE DATABASE IF NOT EXISTS sht DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sht;

-- IDS (ID's)
CREATE TABLE IDS (
  TABLE_NAME varchar(20) NOT NULL COMMENT '테이블명',
  NEXT_ID decimal(30,0) NOT NULL DEFAULT '0' COMMENT '다음 ID',
  PRIMARY KEY (TABLE_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='IDS';

-- COM_TE_COP_SEQ (컴포넌트일련번호)
CREATE TABLE COMTECOPSEQ (
  TABLE_NAME varchar(20) NOT NULL COMMENT '테이블명',
  NEXT_ID decimal(30,0) NOT NULL DEFAULT '0' COMMENT '다음 ID',
  PRIMARY KEY (TABLE_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='컴포넌트일련번호';

-- LET_TC_CMMN_CL_CODE (공통분류코드)
CREATE TABLE LETTCCMMNCLCODE (
  CL_CODE char(3) NOT NULL COMMENT '분류코드',
  CL_CODE_NM varchar(60) DEFAULT NULL COMMENT '분류코드명',
  CL_CODE_DC varchar(200) DEFAULT NULL COMMENT '분류코드설명',
  USE_AT char(1) DEFAULT NULL COMMENT '사용여부',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (CL_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공통분류코드';

-- LET_TC_CMMN_CODE (공통코드)
CREATE TABLE LETTCCMMNCODE (
  CODE_ID varchar(6) NOT NULL COMMENT '코드ID',
  CODE_ID_NM varchar(60) DEFAULT NULL COMMENT '코드ID명',
  CODE_ID_DC varchar(200) DEFAULT NULL COMMENT '코드ID설명',
  USE_AT char(1) DEFAULT NULL COMMENT '사용여부',
  CL_CODE char(3) DEFAULT NULL COMMENT '분류코드',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (CODE_ID),
  KEY R_179 (CL_CODE),
  CONSTRAINT LETTCCMMNCODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES LETTCCMMNCLCODE (CL_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='공통코드'; 

-- LET_TC_CMMN_DETAI_LCODE (공통상세코드)
CREATE TABLE LETTCCMMNDETAILCODE (
  CODE_ID varchar(6) NOT NULL COMMENT '코드ID',
  CODE varchar(15) NOT NULL COMMENT '코드',
  CODE_NM varchar(60) DEFAULT NULL COMMENT '코드명',
  CODE_DC varchar(200) DEFAULT NULL COMMENT '코드설명',
  USE_AT char(1) DEFAULT NULL COMMENT '사용여부',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT LETTCCMMNDETAILCODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES LETTCCMMNCODE (CODE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '공통상세코드';

-- LET_TN_ORGNZT_INFO (조직정보)
CREATE TABLE LETTNORGNZTINFO (
  ORGNZT_ID char(20) NOT NULL DEFAULT '' COMMENT '조직ID',
  ORGNZT_NM varchar(20) NOT NULL COMMENT '조직명',
  ORGNZT_DC varchar(100) DEFAULT NULL COMMENT '조직설명',
  PRIMARY KEY (ORGNZT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '조직정보';

-- LET_TN_AUTHOR_GROUP_INFO (권한그룹정보)
CREATE TABLE LETTNAUTHORGROUPINFO (
  GROUP_ID char(20) NOT NULL DEFAULT '' COMMENT '그룹ID',
  GROUP_NM varchar(60) NOT NULL COMMENT '그룹명',
  GROUP_CREAT_DE char(20) NOT NULL COMMENT '그룹생성일',
  GROUP_DC varchar(100) DEFAULT NULL COMMENT '그룹설명',
  PRIMARY KEY (GROUP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '권한그룹정보';

-- LET_TN_EMPLYR_INFO (업무사용자정보)
CREATE TABLE LETTNEMPLYRINFO (
  EMPLYR_ID varchar(20) NOT NULL COMMENT '업무사용자ID',
  ORGNZT_ID char(20) DEFAULT NULL COMMENT '조직ID',
  USER_NM varchar(60) NOT NULL COMMENT '사용자명',
  PASSWORD varchar(200) NOT NULL COMMENT '비밀번호',
  EMPL_NO varchar(20) DEFAULT NULL COMMENT '사원번호',
  IHIDNUM varchar(200) DEFAULT NULL COMMENT '주민등록번호',
  SEXDSTN_CODE char(1) DEFAULT NULL COMMENT '성별코드',
  BRTHDY char(20) DEFAULT NULL COMMENT '생일',
  FXNUM varchar(20) DEFAULT NULL COMMENT '팩스번호',
  HOUSE_ADRES varchar(100) DEFAULT NULL COMMENT '주택주소',
  PASSWORD_HINT varchar(100) NOT NULL COMMENT '비밀번호힌트',
  PASSWORD_CNSR varchar(100) NOT NULL COMMENT '비밀번호정답',
  HOUSE_END_TELNO varchar(4) DEFAULT NULL COMMENT '주택끝전화번호',
  AREA_NO varchar(4) DEFAULT NULL COMMENT '지역번호',
  DETAIL_ADRES varchar(100) DEFAULT NULL COMMENT '상세주소',
  ZIP varchar(6) DEFAULT NULL COMMENT '우편번호',
  OFFM_TELNO varchar(20) DEFAULT NULL COMMENT '사무실전화번호',
  MBTLNUM varchar(20) DEFAULT NULL COMMENT '이동전화번호',
  EMAIL_ADRES varchar(50) DEFAULT NULL COMMENT '이메일주소',
  OFCPS_NM varchar(60) DEFAULT NULL COMMENT '직위명',
  HOUSE_MIDDLE_TELNO varchar(4) DEFAULT NULL COMMENT '주택중간전화번호',
  GROUP_ID char(20) DEFAULT NULL COMMENT '그룹ID',
  PSTINST_CODE char(8) DEFAULT NULL COMMENT '소속기관코드',
  EMPLYR_STTUS_CODE varchar(15) NOT NULL COMMENT '사용자상태코드',
  ESNTL_ID char(20) NOT NULL COMMENT '고유ID',
  CRTFC_DN_VALUE varchar(20) DEFAULT NULL COMMENT '인증DN값',
  SBSCRB_DE datetime DEFAULT NULL COMMENT '가입일자',
  PRIMARY KEY (EMPLYR_ID),
  KEY LETTNEMPLYRINFO_ibfk_2 (GROUP_ID),
  KEY LETTNEMPLYRINFO_ibfk_1 (ORGNZT_ID),
  CONSTRAINT LETTNEMPLYRINFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT LETTNEMPLYRINFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES LETTNORGNZTINFO (ORGNZT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '업무사용자정보';

-- LET_TN_BBS_MASTER (게시판마스터)
CREATE TABLE LETTNBBSMASTER (
  BBS_ID char(20) NOT NULL COMMENT '게시판ID',
  BBS_NM varchar(255) NOT NULL COMMENT '게시판명',
  BBS_INTRCN varchar(2400) DEFAULT NULL COMMENT '게시판소개',
  BBS_TY_CODE char(6) NOT NULL COMMENT '게시판유형코드',
  BBS_ATTRB_CODE char(6) NOT NULL COMMENT '게시판속성코드',
  REPLY_POSBL_AT char(1) DEFAULT NULL COMMENT '답장가능여부',
  FILE_ATCH_POSBL_AT char(1) NOT NULL COMMENT '파일첨부가능여부',
  ATCH_POSBL_FILE_NUMBER decimal(2,0) NOT NULL COMMENT '첨부가능파일숫자',
  ATCH_POSBL_FILE_SIZE decimal(8,0) DEFAULT NULL COMMENT '첨부가능파일사이즈',
  USE_AT char(1) NOT NULL COMMENT '사용여부',
  TMPLAT_ID char(20) DEFAULT NULL COMMENT '템플릿ID',
  FRST_REGISTER_ID varchar(20) NOT NULL COMMENT '최초등록자ID',
  FRST_REGIST_PNTTM datetime NOT NULL COMMENT '최초등록시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  PRIMARY KEY (BBS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '게시판마스터';

-- LET_TN_BBS_USE (게시판활용)
CREATE TABLE LETTNBBSUSE (
  BBS_ID char(20) NOT NULL COMMENT '게시판ID',
  TRGET_ID char(20) NOT NULL DEFAULT '' COMMENT '대상ID',
  USE_AT char(1) NOT NULL COMMENT '사용여부',
  REGIST_SE_CODE char(6) DEFAULT NULL COMMENT '등록구분코드',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) NOT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT LETTNBBSUSE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '게시판활용';

-- LET_TN_BBS (게시판)
CREATE TABLE LETTNBBS (
  NTT_ID decimal(20,0) NOT NULL COMMENT '게시물ID',
  BBS_ID char(20) NOT NULL COMMENT '게시판ID',
  NTT_NO decimal(20,0) DEFAULT NULL COMMENT '게시물번호',
  NTT_SJ varchar(2000) DEFAULT NULL COMMENT '게시물제목',
  NTT_CN mediumtext COMMENT '게시물내용',
  ANSWER_AT char(1) DEFAULT NULL COMMENT '댓글여부',
  PARNTSCTT_NO decimal(10,0) DEFAULT NULL COMMENT '부모글번호',
  ANSWER_LC int(11) DEFAULT NULL COMMENT '댓글위치',
  SORT_ORDR decimal(8,0) DEFAULT NULL COMMENT '정렬순서',
  RDCNT decimal(10,0) DEFAULT NULL COMMENT '조회수',
  USE_AT char(1) NOT NULL COMMENT '사용여부',
  NTCE_BGNDE char(20) DEFAULT NULL COMMENT '게시시작일',
  NTCE_ENDDE char(20) DEFAULT NULL COMMENT '게시종료일',
  NTCR_ID varchar(20) DEFAULT NULL COMMENT '게시자ID',
  NTCR_NM varchar(20) DEFAULT NULL COMMENT '게시자명',
  PASSWORD varchar(200) DEFAULT NULL COMMENT '비밀번호',
  ATCH_FILE_ID char(20) DEFAULT NULL COMMENT '첨부파일ID',
  FRST_REGIST_PNTTM datetime NOT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) NOT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (NTT_ID,BBS_ID),
  KEY LETTNBBS_ibfk_1 (BBS_ID),
  CONSTRAINT LETTNBBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '게시판';

-- LET_TN_BBS_MASTER_OPTN (게시판마스터옵션)
CREATE TABLE LETTNBBSMASTEROPTN (
  BBS_ID char(20) NOT NULL DEFAULT '' COMMENT '게시판ID',
  ANSWER_AT char(1) NOT NULL DEFAULT '' COMMENT '댓글여부',
  STSFDG_AT char(1) NOT NULL DEFAULT '' COMMENT '만족도여부',
  FRST_REGIST_PNTTM datetime NOT NULL DEFAULT '1900-01-01 00:00:00' COMMENT '최초등록시점',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  FRST_REGISTER_ID varchar(20) NOT NULL DEFAULT '' COMMENT '최초등록자ID',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  PRIMARY KEY (BBS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '게시판마스터옵션'; 

-- LET_TN_ENTRPRS_MBER (기업회원)
CREATE TABLE LETTNENTRPRSMBER (
  ENTRPRS_MBER_ID varchar(20) NOT NULL DEFAULT '' COMMENT '기업회원ID',
  ENTRPRS_SE_CODE char(15) DEFAULT NULL COMMENT '기업구분코드',
  BIZRNO varchar(10) DEFAULT NULL COMMENT '사업자등록번호',
  JURIRNO varchar(13) DEFAULT NULL COMMENT '법인등록번호',
  CMPNY_NM varchar(60) NOT NULL COMMENT '회사명',
  CXFC varchar(50) DEFAULT NULL COMMENT '대표이사',
  ZIP varchar(6) DEFAULT NULL COMMENT '우편번호',
  ADRES varchar(100) DEFAULT NULL COMMENT '주소',
  ENTRPRS_MIDDLE_TELNO varchar(4) DEFAULT NULL COMMENT '기업중간전화번호',
  FXNUM varchar(20) DEFAULT NULL COMMENT '팩스번호',
  INDUTY_CODE char(15) DEFAULT NULL COMMENT '업종코드',
  APPLCNT_NM varchar(50) DEFAULT NULL COMMENT '신청인명',
  APPLCNT_IHIDNUM varchar(200) DEFAULT NULL COMMENT '신청인주민등록번호',
  SBSCRB_DE datetime DEFAULT NULL COMMENT '가입일자',
  ENTRPRS_MBER_STTUS varchar(15) DEFAULT NULL COMMENT '기업회원상태',
  ENTRPRS_MBER_PASSWORD varchar(200) NOT NULL COMMENT '기업회원비밀번호',
  ENTRPRS_MBER_PASSWORD_HINT varchar(100) NOT NULL COMMENT '기업회원비밀번호힌트',
  ENTRPRS_MBER_PASSWORD_CNSR varchar(100) NOT NULL COMMENT '기업회원비밀번호정답',
  GROUP_ID char(20) DEFAULT NULL COMMENT '그룹ID',
  DETAIL_ADRES varchar(100) DEFAULT NULL COMMENT '상세주소',
  ENTRPRS_END_TELNO varchar(4) DEFAULT NULL COMMENT '기업끝전화번호',
  AREA_NO varchar(4) DEFAULT NULL COMMENT '지역번호',
  APPLCNT_EMAIL_ADRES varchar(50) DEFAULT NULL COMMENT '신청자이메일주소',
  ESNTL_ID char(20) NOT NULL COMMENT '고유ID',
  PRIMARY KEY (ENTRPRS_MBER_ID),
  KEY LETTNENTRPRSMBER_ibfk_1 (GROUP_ID),
  CONSTRAINT LETTNENTRPRSMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '기업회원';

-- LET_TN_FILE (파일속성)
CREATE TABLE LETTNFILE (
  ATCH_FILE_ID char(20) NOT NULL COMMENT '첨부파일ID',
  CREAT_DT datetime NOT NULL COMMENT '생성일시',
  USE_AT char(1) DEFAULT NULL COMMENT '사용여부',
  PRIMARY KEY (ATCH_FILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '파일속성';

-- LET_TN_FILE_DETAIL (파일상세정보)
CREATE TABLE LETTNFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL COMMENT '첨부파일ID',
  FILE_SN decimal(10,0) NOT NULL COMMENT '파일순번',
  FILE_STRE_COURS varchar(2000) NOT NULL COMMENT '파일저장경로',
  STRE_FILE_NM varchar(255) NOT NULL COMMENT '저장파일명',
  ORIGNL_FILE_NM varchar(255) DEFAULT NULL COMMENT '원파일명',
  FILE_EXTSN varchar(20) NOT NULL COMMENT '파일확장자',
  FILE_CN mediumtext COMMENT '파일내용',
  FILE_SIZE decimal(8,0) DEFAULT NULL COMMENT '파일크기',
  PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT LETTNFILEDETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES LETTNFILE (ATCH_FILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '파일상세정보';

-- LET_TN_GNRL_MBER (일반회원)
CREATE TABLE LETTNGNRLMBER (
  MBER_ID varchar(20) NOT NULL DEFAULT '' COMMENT '회원ID',
  PASSWORD varchar(200) NOT NULL COMMENT '비밀번호',
  PASSWORD_HINT varchar(100) DEFAULT NULL COMMENT '비밀번호힌트',
  PASSWORD_CNSR varchar(100) DEFAULT NULL COMMENT '비밀번호정답',
  IHIDNUM varchar(200) DEFAULT NULL COMMENT '주민등록번호',
  MBER_NM varchar(50) NOT NULL COMMENT '회원명',
  ZIP varchar(6) DEFAULT NULL COMMENT '우편번호',
  ADRES varchar(100) DEFAULT NULL COMMENT '주소',
  AREA_NO varchar(4) DEFAULT NULL COMMENT '지역번호',
  MBER_STTUS varchar(15) DEFAULT NULL COMMENT '회원상태',
  DETAIL_ADRES varchar(100) DEFAULT NULL COMMENT '상세주소',
  END_TELNO varchar(4) DEFAULT NULL COMMENT '끝전화번호',
  MBTLNUM varchar(20) DEFAULT NULL COMMENT '이동전화번호',
  GROUP_ID char(20) DEFAULT NULL COMMENT '그룹ID',
  MBER_FXNUM varchar(20) DEFAULT NULL COMMENT '회원팩스번호',
  MBER_EMAIL_ADRES varchar(50) DEFAULT NULL COMMENT '회원이메일주소',
  MIDDLE_TELNO varchar(4) DEFAULT NULL COMMENT '중간전화번호',
  SBSCRB_DE datetime DEFAULT NULL COMMENT '가입일자',
  SEXDSTN_CODE char(1) DEFAULT NULL COMMENT '성별코드',
  ESNTL_ID char(20) NOT NULL COMMENT '고유ID',
  PRIMARY KEY (MBER_ID),
  KEY LETTNGNRLMBER_ibfk_1 (GROUP_ID),
  CONSTRAINT LETTNGNRLMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '일반회원';

-- LET_TN_SCHDUL_INFO (일정정보)
CREATE TABLE LETTNSCHDULINFO (
  SCHDUL_ID char(20) NOT NULL COMMENT '일정ID',
  SCHDUL_SE char(1) DEFAULT NULL COMMENT '일정구분',
  SCHDUL_DEPT_ID varchar(20) DEFAULT NULL COMMENT '일정부서ID',
  SCHDUL_KND_CODE varchar(20) DEFAULT NULL COMMENT '일정종류코드',
  SCHDUL_BEGINDE datetime DEFAULT NULL COMMENT '일정시작일',
  SCHDUL_ENDDE datetime DEFAULT NULL COMMENT '일정종료일',
  SCHDUL_NM varchar(255) DEFAULT NULL COMMENT '일정명',
  SCHDUL_CN varchar(2500) DEFAULT NULL COMMENT '일정내용',
  SCHDUL_PLACE varchar(255) DEFAULT NULL COMMENT '일정장소',
  SCHDUL_IPCR_CODE char(1) DEFAULT NULL COMMENT '일정중요도코드',
  SCHDUL_CHARGER_ID varchar(20) DEFAULT NULL COMMENT '일정담당자ID',
  ATCH_FILE_ID char(20) DEFAULT NULL COMMENT '첨부파일ID',
  FRST_REGIST_PNTTM datetime DEFAULT NULL COMMENT '최초등록시점',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL COMMENT '최초등록자ID',
  LAST_UPDT_PNTTM datetime DEFAULT NULL COMMENT '최종수정시점',
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL COMMENT '최종수정자ID',
  REPTIT_SE_CODE char(3) DEFAULT NULL COMMENT '반복구분코드',
  PRIMARY KEY (SCHDUL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '일정정보';

-- View COM_VN_USER_MASTER
CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM LETTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNENTRPRSMBER 
;