-- IDS (ID's)
CREATE TABLE IDS  (
  TABLE_NAME varchar(60) NOT NULL,
  NEXT_ID numeric(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);
-- 테이블 설명 추가
CREATE COMMENT ON IDS IS 'IDS';
-- 컬럼 설명 추가
CREATE COMMENT ON COLUMN IDS.TABLE_NAME IS '테이블명';
CREATE COMMENT ON COLUMN IDS.NEXT_ID IS '다음 ID';

-- COM_TE_COP_SEQ (컴포넌트일련번호)
CREATE TABLE COMTECOPSEQ  (
  TABLE_NAME varchar(60) NOT NULL,
  NEXT_ID numeric(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME)
);
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE COMTECOPSEQ IS '컴포넌트일련번호'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN COMTECOPSEQ.TABLE_NAME IS '테이블명'; 
CREATE COMMENT ON COLUMN COMTECOPSEQ.NEXT_ID IS '다음아이디'; 

-- LET_TC_CMMN_CL_CODE (공통분류코드)
CREATE TABLE LETTCCMMNCLCODE (
  CL_CODE char(3) NOT NULL,
  CL_CODE_NM varchar(180) ,
  CL_CODE_DC varchar(600) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTCCMMNCLCODE_PK PRIMARY KEY (CL_CODE)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTCCMMNCLCODE IS '공통분류코드'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.CL_CODE IS '분류코드'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.CL_CODE_NM IS '분류코드명'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.CL_CODE_DC IS '분류코드설명'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTCCMMNCLCODE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TC_CMMN_CODE (공통코드)
CREATE TABLE LETTCCMMNCODE  (
  CODE_ID varchar(18) NOT NULL,
  CODE_ID_NM varchar(180) ,
  CODE_ID_DC varchar(600) ,
  USE_AT char(1) ,
  CL_CODE char(3) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTCCMMNCODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT LETTCCMMNCODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES LETTCCMMNCLCODE (CL_CODE)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTCCMMNCODE IS '공통코드';
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTCCMMNCODE.CODE_ID IS '코드ID'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.CODE_ID_NM IS '코드ID명'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.CODE_ID_DC IS '코드ID설명'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.CL_CODE IS '분류코드'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTCCMMNCODE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TC_CMMN_DETAI_LCODE (공통상세코드)
CREATE TABLE LETTCCMMNDETAILCODE  (
  CODE_ID varchar(18) NOT NULL,
  CODE varchar(45) NOT NULL,
  CODE_NM varchar(180) ,
  CODE_DC varchar(600) ,
  USE_AT char(1) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT LETTCCMMNDETAILCODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES LETTCCMMNCODE (CODE_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTCCMMNDETAILCODE IS '공통상세코드'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.CODE_ID IS '코드ID'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.CODE IS '코드'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.CODE_NM IS '코드명'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.CODE_DC IS '코드설명'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTCCMMNDETAILCODE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_ORGNZT_INFO (조직정보)
CREATE TABLE LETTNORGNZTINFO  (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,
  ORGNZT_NM varchar(60) NOT NULL,
  ORGNZT_DC varchar(300) ,
  CONSTRAINT LETTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNORGNZTINFO IS '조직정보'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNORGNZTINFO.ORGNZT_ID IS '조직ID'; 
CREATE COMMENT ON COLUMN LETTNORGNZTINFO.ORGNZT_NM IS '조직명'; 
CREATE COMMENT ON COLUMN LETTNORGNZTINFO.ORGNZT_DC IS '조직설명'; 

-- LET_TN_AUTHOR_GROUP_INFO (권한그룹정보)
CREATE TABLE LETTNAUTHORGROUPINFO  (
  GROUP_ID char(20) DEFAULT '' NOT NULL,
  GROUP_NM varchar(180) NOT NULL,
  GROUP_CREAT_DE char(60) NOT NULL,
  GROUP_DC varchar(300) ,
  CONSTRAINT LETTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNAUTHORGROUPINFO IS '권한그룹정보'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNAUTHORGROUPINFO.GROUP_ID IS '그룹ID'; 
CREATE COMMENT ON COLUMN LETTNAUTHORGROUPINFO.GROUP_NM IS '그룹명'; 
CREATE COMMENT ON COLUMN LETTNAUTHORGROUPINFO.GROUP_CREAT_DE IS '그룹생성일'; 
CREATE COMMENT ON COLUMN LETTNAUTHORGROUPINFO.GROUP_DC IS '그룹설명';

-- LET_TN_EMPLYR_INFO (업무사용자정보)
CREATE TABLE LETTNEMPLYRINFO  (
  EMPLYR_ID varchar(60) NOT NULL,
  ORGNZT_ID char(20) ,
  USER_NM varchar(180) NOT NULL,
  PASSWORD varchar(600) NOT NULL,
  EMPL_NO varchar(60) ,
  IHIDNUM varchar(39) ,
  SEXDSTN_CODE char(1) ,
  BRTHDY char(20) ,
  FXNUM varchar(60) ,
  HOUSE_ADRES varchar(300) ,
  PASSWORD_HINT varchar(300) NOT NULL,
  PASSWORD_CNSR varchar(300) NOT NULL,
  HOUSE_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  DETAIL_ADRES varchar(300) ,
  ZIP varchar(18) ,
  OFFM_TELNO varchar(60) ,
  MBTLNUM varchar(60) ,
  EMAIL_ADRES varchar(150) ,
  OFCPS_NM varchar(180) ,
  HOUSE_MIDDLE_TELNO varchar(12) ,
  GROUP_ID char(20) ,
  PSTINST_CODE char(8) ,
  EMPLYR_STTUS_CODE varchar(45) NOT NULL,
  ESNTL_ID char(20) NOT NULL,
  CRTFC_DN_VALUE varchar(60) ,
  SBSCRB_DE DATETIME ,
  CONSTRAINT LETTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT LETTNEMPLYRINFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT LETTNEMPLYRINFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES LETTNORGNZTINFO (ORGNZT_ID) ON DELETE CASCADE
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNEMPLYRINFO IS '업무사용자정보'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.EMPLYR_ID IS '업무사용자ID'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.ORGNZT_ID IS '조직ID'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.USER_NM IS '사용자명'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.PASSWORD IS '비밀번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.EMPL_NO IS '사원번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.IHIDNUM IS '주민등록번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.SEXDSTN_CODE IS '성별코드'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.BRTHDY IS '생일'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.FXNUM IS '팩스번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.HOUSE_ADRES IS '주택주소'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.PASSWORD_HINT IS '비밀번호힌트'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.PASSWORD_CNSR IS '비밀번호정답'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.HOUSE_END_TELNO IS '주택끝전화번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.AREA_NO IS '지역번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.DETAIL_ADRES IS '상세주소'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.ZIP IS '우편번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.OFFM_TELNO IS '사무실전화번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.MBTLNUM IS '이동전화번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.EMAIL_ADRES IS '이메일주소'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.OFCPS_NM IS '직위명'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.HOUSE_MIDDLE_TELNO IS '주택중간전화번호'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.GROUP_ID IS '그룹ID'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.PSTINST_CODE IS '소속기관코드'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.EMPLYR_STTUS_CODE IS '사용자상태코드'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.ESNTL_ID IS '고유ID'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.CRTFC_DN_VALUE IS '인증DN값'; 
CREATE COMMENT ON COLUMN LETTNEMPLYRINFO.SBSCRB_DE IS '가입일자'; 

-- LET_TN_BBS_MASTER (게시판마스터)
CREATE TABLE LETTNBBSMASTER  (
  BBS_ID char(20) NOT NULL,
  BBS_NM varchar(765) NOT NULL,
  BBS_INTRCN varchar(7200) ,
  BBS_TY_CODE char(6) NOT NULL,
  BBS_ATTRB_CODE char(6) NOT NULL,
  REPLY_POSBL_AT char(1) ,
  FILE_ATCH_POSBL_AT char(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER numeric(2,0) NOT NULL,
  ATCH_POSBL_FILE_SIZE numeric(8,0) ,
  USE_AT char(1) NOT NULL,
  TMPLAT_ID char(20) ,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  LAST_UPDUSR_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  CONSTRAINT LETTNBBSMASTER_PK PRIMARY KEY (BBS_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNBBSMASTER IS '게시판마스터'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNBBSMASTER.BBS_ID IS '게시판ID'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.BBS_NM IS '게시판명'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.BBS_INTRCN IS '게시판소개'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.BBS_TY_CODE IS '게시판유형코드'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.REPLY_POSBL_AT IS '답장가능여부'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.FILE_ATCH_POSBL_AT IS '파일첨부가능여부'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.ATCH_POSBL_FILE_NUMBER IS '첨부가능파일숫자'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.ATCH_POSBL_FILE_SIZE IS '첨부가능파일사이즈'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.TMPLAT_ID IS '템플릿ID'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.LAST_UPDUSR_ID IS '최종수정자ID'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTER.LAST_UPDT_PNTTM IS '최종수정시점'; 

-- LET_TN_BBS_USE (게시판활용)
CREATE TABLE LETTNBBSUSE  (
  BBS_ID char(20) NOT NULL,
  TRGET_ID char(20) DEFAULT '' NOT NULL,
  USE_AT char(1) NOT NULL,
  REGIST_SE_CODE char(6) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTNBBSUSE_PK PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT LETTNBBSUSE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNBBSUSE IS '게시판활용'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNBBSUSE.BBS_ID IS '게시판ID'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.TRGET_ID IS '대상ID'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.REGIST_SE_CODE IS '등록구분코드'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTNBBSUSE.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_BBS (게시판)
CREATE TABLE LETTNBBS (
  NTT_ID numeric(20,0) NOT NULL,
  BBS_ID char(20) NOT NULL,
  NTT_NO numeric(20,0) ,
  NTT_SJ varchar(6000) ,
  NTT_CN STRING,
  ANSWER_AT char(1) ,
  PARNTSCTT_NO numeric(10,0) ,
  ANSWER_LC numeric(11) ,
  SORT_ORDR numeric(8,0) ,
  RDCNT numeric(10,0) ,
  USE_AT char(1) NOT NULL,
  NTCE_BGNDE char(20) ,
  NTCE_ENDDE char(20) ,
  NTCR_ID varchar(60) ,
  NTCR_NM varchar(60) ,
  PASSWORD varchar(600) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  FRST_REGISTER_ID varchar(60) NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTNBBS_PK PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT LETTNBBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES LETTNBBSMASTER (BBS_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNBBS IS '게시판'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNBBS.NTT_ID IS '게시물ID'; 
CREATE COMMENT ON COLUMN LETTNBBS.BBS_ID IS '게시판ID'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTT_NO IS '게시물번호'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTT_SJ IS '게시물제목'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTT_CN IS '게시물내용'; 
CREATE COMMENT ON COLUMN LETTNBBS.ANSWER_AT IS '댓글여부'; 
CREATE COMMENT ON COLUMN LETTNBBS.PARNTSCTT_NO IS '부모글번호'; 
CREATE COMMENT ON COLUMN LETTNBBS.ANSWER_LC IS '댓글위치'; 
CREATE COMMENT ON COLUMN LETTNBBS.SORT_ORDR IS '정렬순서'; 
CREATE COMMENT ON COLUMN LETTNBBS.USE_AT IS '사용여부'; 
CREATE COMMENT ON COLUMN LETTNBBS.RDCNT IS '조회수'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTCE_BGNDE IS '게시시작일'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTCE_ENDDE IS '게시종료일'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTCR_ID IS '게시자ID'; 
CREATE COMMENT ON COLUMN LETTNBBS.NTCR_NM IS '게시자명'; 
CREATE COMMENT ON COLUMN LETTNBBS.PASSWORD IS '비밀번호'; 
CREATE COMMENT ON COLUMN LETTNBBS.ATCH_FILE_ID IS '첨부파일ID'; 
CREATE COMMENT ON COLUMN LETTNBBS.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTNBBS.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTNBBS.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTNBBS.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_BBS_MASTER_OPTN (게시판마스터옵션)
CREATE TABLE LETTNBBSMASTEROPTN (
  BBS_ID char(20) DEFAULT '' NOT NULL,
  ANSWER_AT char(1) DEFAULT '' NOT NULL,
  STSFDG_AT char(1) DEFAULT '' NOT NULL,
  FRST_REGIST_PNTTM DATETIME DEFAULT SYSDATE NOT NULL,
  LAST_UPDT_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) DEFAULT '' NOT NULL,
  LAST_UPDUSR_ID varchar(60) ,
  CONSTRAINT LETTNBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNBBSMASTEROPTN IS '게시판마스터옵션'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.BBS_ID IS '게시판ID'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.ANSWER_AT IS '댓글여부'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.STSFDG_AT IS '만족도여부'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.FRST_REGIST_PNTTM IS '최초등록시점'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.LAST_UPDT_PNTTM IS '최종수정시점'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.FRST_REGISTER_ID IS '최초등록자ID'; 
CREATE COMMENT ON COLUMN LETTNBBSMASTEROPTN.LAST_UPDUSR_ID IS '최종수정자ID'; 

-- LET_TN_ENTRPRS_MBER (기업회원)
CREATE TABLE LETTNENTRPRSMBER (
  ENTRPRS_MBER_ID varchar(60) DEFAULT '' NOT NULL,
  ENTRPRS_SE_CODE char(15) ,
  BIZRNO varchar(30) ,
  JURIRNO varchar(39) ,
  CMPNY_NM varchar(180) NOT NULL,
  CXFC varchar(150) ,
  ZIP varchar(18) ,
  ADRES varchar(300) ,
  ENTRPRS_MIDDLE_TELNO varchar(12) ,
  FXNUM varchar(60) ,
  INDUTY_CODE char(15) ,
  APPLCNT_NM varchar(150) NOT NULL,
  APPLCNT_IHIDNUM varchar(39) ,
  SBSCRB_DE DATETIME ,
  ENTRPRS_MBER_STTUS varchar(45) ,
  ENTRPRS_MBER_PASSWORD varchar(600) NOT NULL,
  ENTRPRS_MBER_PASSWORD_HINT varchar(300) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR varchar(300) NOT NULL,
  GROUP_ID char(20) ,
  DETAIL_ADRES varchar(300) ,
  ENTRPRS_END_TELNO varchar(12) ,
  AREA_NO varchar(12) ,
  APPLCNT_EMAIL_ADRES varchar(150) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT LETTNENTRPRSMBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT LETTNENTRPRSMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNENTRPRSMBER IS '기업회원'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_ID IS '기업회원ID'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_SE_CODE IS '기업구분코드'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.BIZRNO IS '사업자등록번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.JURIRNO IS '법인등록번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.CMPNY_NM IS '회사명'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.CXFC IS '대표이사'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ZIP IS '우편번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ADRES IS '주소'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MIDDLE_TELNO IS '기업중간전화번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.FXNUM IS '팩스번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.INDUTY_CODE IS '업종코드'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.APPLCNT_NM IS '신청인명'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.APPLCNT_IHIDNUM IS '신청인주민등록번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.SBSCRB_DE IS '가입일자'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_STTUS IS '기업회원상태'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD IS '기업회원비밀번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD_HINT IS '기업회원비밀번호힌트'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_MBER_PASSWORD_CNSR IS '기업회원비밀번호정답'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.GROUP_ID IS '그룹ID'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.DETAIL_ADRES IS '상세주소'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ENTRPRS_END_TELNO IS '기업끝전화번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.AREA_NO IS '지역번호'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.APPLCNT_EMAIL_ADRES IS '신청자이메일주소'; 
CREATE COMMENT ON COLUMN LETTNENTRPRSMBER.ESNTL_ID IS '고유ID'; 

-- LET_TN_FILE (파일속성)
CREATE TABLE LETTNFILE (
  ATCH_FILE_ID char(20) NOT NULL,
  CREAT_DT DATETIME NOT NULL,
  USE_AT char(1) ,
  CONSTRAINT LETTNFILE_PK PRIMARY KEY (ATCH_FILE_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNFILE IS '파일속성'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNFILE.ATCH_FILE_ID IS '첨부파일ID'; 
CREATE COMMENT ON COLUMN LETTNFILE.CREAT_DT IS '생성일시'; 
CREATE COMMENT ON COLUMN LETTNFILE.USE_AT IS '사용여부'; 

-- LET_TN_FILE_DETAIL (파일상세정보)
CREATE TABLE LETTNFILEDETAIL (
  ATCH_FILE_ID char(20) NOT NULL,
  FILE_SN numeric(10,0) NOT NULL,
  FILE_STRE_COURS varchar(6000) NOT NULL,
  STRE_FILE_NM varchar(765) NOT NULL,
  ORIGNL_FILE_NM varchar(765) ,
  FILE_EXTSN varchar(60) NOT NULL,
  FILE_CN STRING,
  FILE_SIZE numeric(8,0) ,
  CONSTRAINT LETTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
  CONSTRAINT LETTNFILEDETAIL_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES LETTNFILE (ATCH_FILE_ID)
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNFILEDETAIL IS '파일상세정보'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.ATCH_FILE_ID IS '첨부파일ID'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.FILE_SN IS '파일순번'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.FILE_STRE_COURS IS '파일저장경로'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.STRE_FILE_NM IS '저장파일명'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.ORIGNL_FILE_NM IS '원파일명'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.FILE_EXTSN IS '파일확장자'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.FILE_CN IS '파일내용'; 
CREATE COMMENT ON COLUMN LETTNFILEDETAIL.FILE_SIZE IS '파일크기'; 

-- LET_TN_GNRL_MBER (일반회원)
CREATE TABLE LETTNGNRLMBER (
  MBER_ID varchar(60) DEFAULT '' NOT NULL,
  PASSWORD varchar(600) NOT NULL,
  PASSWORD_HINT varchar(300) NOT NULL,
  PASSWORD_CNSR varchar(300) NOT NULL,
  IHIDNUM varchar(39) ,
  MBER_NM varchar(150) NOT NULL,
  ZIP varchar(18) ,
  ADRES varchar(300) ,
  AREA_NO varchar(12) ,
  MBER_STTUS varchar(45) ,
  DETAIL_ADRES varchar(300) ,
  END_TELNO varchar(12) ,
  MBTLNUM varchar(60) ,
  GROUP_ID char(20) ,
  MBER_FXNUM varchar(60) ,
  MBER_EMAIL_ADRES varchar(150) ,
  MIDDLE_TELNO varchar(12) ,
  SBSCRB_DE DATETIME ,
  SEXDSTN_CODE char(1) ,
  ESNTL_ID char(20) NOT NULL,
  CONSTRAINT LETTNGNRLMBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT LETTNGNRLMBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES LETTNAUTHORGROUPINFO (GROUP_ID) ON DELETE CASCADE
) ;
-- 테이블에 대한 설명
CREATE COMMENT ON TABLE LETTNGNRLMBER IS '일반회원'; 
-- 컬럼에 대한 설명
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MBER_ID IS '회원ID'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.PASSWORD IS '비밀번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.PASSWORD_HINT IS '비밀번호힌트'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.PASSWORD_CNSR IS '비밀번호정답'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.IHIDNUM IS '주민등록번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MBER_NM IS '회원명'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.ZIP IS '우편번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.ADRES IS '주소'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.AREA_NO IS '지역번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MBER_STTUS IS '회원상태'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.DETAIL_ADRES IS '상세주소'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.END_TELNO IS '끝전화번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MBTLNUM IS '이동전화번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.GROUP_ID IS '그룹ID'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MBER_FXNUM IS '회원팩스번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MBER_EMAIL_ADRES IS '회원이메일주소'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.MIDDLE_TELNO IS '중간전화번호'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.SBSCRB_DE IS '가입일자'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.SEXDSTN_CODE IS '성별코드'; 
CREATE COMMENT ON COLUMN LETTNGNRLMBER.ESNTL_ID IS '고유ID'; 

-- LET_TN_SCHDUL_INFO (일정정보)
CREATE TABLE LETTNSCHDULINFO (
  SCHDUL_ID char(20) NOT NULL,
  SCHDUL_SE char(1) ,
  SCHDUL_DEPT_ID varchar(60) ,
  SCHDUL_KND_CODE varchar(60) ,
  SCHDUL_BEGINDE char(40) ,
  SCHDUL_ENDDE char(40) ,
  SCHDUL_NM varchar(765) ,
  SCHDUL_CN varchar(7500) ,
  SCHDUL_PLACE varchar(765) ,
  SCHDUL_IPCR_CODE char(1) ,
  SCHDUL_CHARGER_ID varchar(60) ,
  ATCH_FILE_ID char(20) ,
  FRST_REGIST_PNTTM DATETIME ,
  FRST_REGISTER_ID varchar(60) ,
  LAST_UPDT_PNTTM DATETIME ,
  LAST_UPDUSR_ID varchar(60) ,
  REPTIT_SE_CODE char(3) ,
  CONSTRAINT LETTNSCHDULINFO_PK PRIMARY KEY (SCHDUL_ID)
) ;
-- 테이블에 대한 설명
COMMENT ON TABLE LETTNSCHDULINFO IS '일정정보'; 
-- 컬럼에 대한 설명
COMMENT ON COLUMN LETTNSCHDULINFO.SCHDUL_ID IS '일정ID'; 
COMMENT ON COLUMN LETTNSCHDULINFO.SCHDUL_SE IS '일정구분'; 
COMMENT ON COLUMN LETTNSCHDULINFO.SCHDUL_DEPT_ID IS '일정부서ID'; 
COMMENT ON COLUMN LETTNSCHDULINFO.SCHDUL_KND_CODE IS '일정종류코드'; 
COMMENT ON COLUMN LETTNSCHDULINFO.SCHDUL_BGNDE IS '일정시작일'; 
COMMENT ON COLUMN LETTNSCHDULINFO.SCHDUL_ENDDE IS '일정종료일'; 
COMMENT ON COLUMN LETTNSCHDULINFO.SCHDUL_NM IS '일정명'; 
COMMENT ON COLUMN LETTNSCHDULINFO.SCHDUL_CN IS '일정내용'; 
COMMENT ON COLUMN LETTNSCHDULINFO.SCHDUL_PLACE IS '일정장소'; 
COMMENT ON COLUMN LETTNSCHDULINFO.SCHDUL_IPCR_CODE IS '일정중요도코드'; 
COMMENT ON COLUMN LETTNSCHDULINFO.SCHDUL_CHARGER_ID IS '일정담당자ID'; 
COMMENT ON COLUMN LETTNSCHDULINFO.ATCH_FILE_ID IS '첨부파일ID'; 
COMMENT ON COLUMN LETTNSCHDULINFO.FRST_REGIST_PNTTM IS '최초등록시점'; 
COMMENT ON COLUMN LETTNSCHDULINFO.FRST_REGISTER_ID IS '최초등록자ID'; 
COMMENT ON COLUMN LETTNSCHDULINFO.LAST_UPDT_PNTTM IS '최종수정시점'; 
COMMENT ON COLUMN LETTNSCHDULINFO.LAST_UPDUSR_ID IS '최종수정자ID'; 
COMMENT ON COLUMN LETTNSCHDULINFO.REPTIT_SE_CODE IS '반복구분코드'; 

-- View COM_VN_USER_MASTER
CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM LETTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM LETTNENTRPRSMBER 
;